### ISSUE TITLE
Error: Unsupported Media Type

### ISSUE THREAD

**Issue by alphatrianguli** [fabieu/sureflap-api#25]
Since last night, all API calls return the following:

{"detail":"{'type':'https://tools.ietf.org/html/rfc7231#section-6.5.13','title':'Unsupported Media Type','status':415,'traceId':'00-f24ad9b63830f2cc9b87a1130cc273ed-62d77ac71f34f4b9-00'}"}

Anybody have an idea whats wrong? Something maybe changed on the side of SurePet / SureFlap?

**Comment by alphatrianguli** [comment]
Just saw that you did some updates of your software :) I pulled the newest docker and now get the following logs, somehow different than before but still getting the same error:

`INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3001 (Press CTRL+C to quit)
INFO:     192.168.0.6:36202 - "GET /households/xxxxxx/pets/location HTTP/1.1" 415 Unsupported Media Type
INFO:     192.168.0.5:61981 - "GET / HTTP/1.1" 307 Temporary Redirect
INFO:     192.168.0.5:61981 - "GET /docs HTTP/1.1" 200 OK
INFO:     192.168.0.5:61981 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     192.168.0.5:61981 - "GET /dashboard HTTP/1.1" 415 Unsupported Media Type
INFO:     192.168.0.5:61989 - "GET /households HTTP/1.1" 415 Unsupported Media Type
INFO:     192.168.0.6:51750 - "GET /households/xxxxxx/pets/location HTTP/1.1" 415 Unsupported Media Type
INFO:     192.168.0.6:43940 - "GET /households/xxxxxx/pets/location HTTP/1.1" 415 Unsupported Media Type
`

**Comment by fabieu** [comment]
I am currently investigating the issue. It seems that something changed in the login process which prohibits all further requests since the login has to be done at least once.

**Comment by alphatrianguli** [comment]
Not sure if it helps, but according to SurePy users, the login URL might have changed?

https://github.com/benleb/surepy/issues/199

**Comment by fabieu** [comment]
> Not sure if it helps, but according to SurePy users, the login URL might have changed?
> 
> [benleb/surepy#199](https://github.com/benleb/surepy/issues/199)

I also noticed the change in the Login-URL. It seems the folks at SurePetcare are now doing Blue/Green-Deployments of their Login-Backend :)

**Comment by fabieu** [comment]
Unfortunately, replacing the endpoint url is not enough to solve the problem. But I will definitely tackle this in the next few days.

**Comment by alphatrianguli** [comment]
> Unfortunately, replacing the endpoint url is not enough to solve the problem. But I will definitely tackle this in the next few days.

No worries, let me know if I can support you with testing etc.

**Comment by Stono** [comment]
:wave: happy to beta test a pre-release too

**Comment by fabieu** [comment]
> 👋 happy to beta test a pre-release too



> > Unfortunately, replacing the endpoint url is not enough to solve the problem. But I will definitely tackle this in the next few days.
> 
> No worries, let me know if I can support you with testing etc.

I just released a new version which should fix the issue. It would be awesome , if you can provide some feedback.

**Comment by alphatrianguli** [comment]
> I just released a new version which should fix the issue. It would be awesome , if you can provide some feedback. @Stono @alphatrianguli

Did you also update the docker image? Repulled the docker image but still getting the same errors :/

**Comment by fabieu** [comment]
Currently having some issues with aaarch32 and aarch64 docker images. Working on a fix.

**Comment by alphatrianguli** [comment]
> Currently having some issues with aaarch32 and aarch64 docker images. Working on a fix.

Ok, no hurry. Thanks for looking into it!

**Comment by fabieu** [comment]
> > Currently having some issues with aaarch32 and aarch64 docker images. Working on a fix.
> 
> Ok, no hurry. Thanks for looking into it!

As a temporary workaround you could build the docker image yourself on the target matchine by cloning the repository and running `docker build -t fabieu/sureflap-api .`

**Comment by alphatrianguli** [comment]
@fabieu Thanks for fixing the issue, I just pulled the latest docker image and everything seems to be working again:

![image](https://github.com/fabieu/sureflap-api/assets/37271879/0731e885-e4f3-4498-ba43-86b67c9135d9)

I will keep an eye on it the next days. Many thanks for your quick support! 👍
