### ISSUE TITLE
Cannot control the lock status

### ISSUE THREAD

**Issue by Vandroiy78** [fabieu/sureflap-api#27]
Hi

Thank you very much for developing this piece of software :-)
I have installed the docker variant and I can run all the GET commands just fine.

However if I try to change the lock state on one of my flaps, I receive an http/422 error:

Request: {{baseUrl}}/devices/:device_id/control?lock_mode=out

Response
{
    "detail": "{'success':false,'error':{}}"
}

Performing a GET on the device_id returns a result as expected.

Thank you for any help.

Holger

**Comment by fabieu** [comment]
Hey @Vandroiy78,

thank you for your contribution. I suspect that your SurePetCare User doesn't have the "Control Permissions" required for updating the lock state. Nevertheless, the HTTP status code would be misleading in this case.

 I'll take a closer look tomorrow and share my findings.
 
 Kind regards
 Fabian

**Comment by Vandroiy78** [comment]
Thank you for your response, Fabian. 

I am able to control the locking state via the app or website with this user. However this is not the main user of the system, but granted administrator privilege. 

I will see if it works when using the main user. 

Holger

**Comment by fabieu** [comment]
I could reproduce the issue on my own SureFlap device. It has nothing to do with permissions.

I just want to let you know that I am working on a fix.

**Comment by fabieu** [comment]
Hey @Vandroiy78 

The issue should be resolved with [Release 4.2.4](https://gitlab.com/sustineo/sureflap-api/-/releases/4.2.4). The docker images are available.

Just let me know, if you can control the lock state now.

Kind regards
Fabian

**Comment by Vandroiy78** [comment]
Hello Fabian

Thank you so much for taking care about this issue. I have updated to the latest version.

At this moment, I still get valid results for all the GET commands. When trying to set the lock mode I have:
`{
  "detail": "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n"
}`

I will retry tomorrow, maybe there is a problem with their servers.

Regards
Holger

**Comment by Vandroiy78** [comment]
It seems that they indeed had outage on their system yesterday. 

I re-tried today and I still get the error above sometimes, but in other tries I receive an error 500 while the lock state is set correctly. Maybe they are still recovering from the outage and are receiving lots of loads on their servers.

I think that the initial problem has been solved. Thank you, @fabieu

**Comment by fabieu** [comment]
I sometimes experience the described behavior via the official SureFlap Android app as well.

Unfortunately, there is nothing I can do to prevent this, so I will close this issue as resolved.

**Comment by julianwachholz** [comment]
Hi @fabieu thank you for this project! I've been looking for a way to add a additional curfew modes for our cats (like lock-outside curfew which is supported on the non-connected flaps!) and this would be perfect.

After a quick test it looks like my `GET /device/<id>` returns invalid/incomplete data and setting a `lock_mode` doesn't work on my device either.

I did a `GET /devices/<id>` when the device was set to "Locked both ways" in the app:

```json
{
  "control": {
    "curfew": null,
    "fast_polling": null,
    "locking": null
  },
  "created_at": "2019-09-03TXX:XX:XXZ",
  "household_id": 0.0,
  "id": 0.0,
  "index": null,
  "mac_adress": null,
  "name": "Hub",
  "pairing_at": null,
  "parent": null,
  "parent_device_id": null,
  "product_id": 1.0,
  "status": {
    "battery": null,
    "learn_mode": null,
    "locking": null,
    "online": true,
    "signal": null,
    "version": {
      "lcd": null,
      "rf": null
    }
  },
  "updated_at": "2024-06-13T05:49:05.498102Z",
  "version": 38829.0
}
```

And after this
```
curl -X PATCH http://localhost:8080/devices/<id>/control?lock_mode=none
{"curfew":null,"fast_polling":null,"locking":null}
```

Nothing in the output changes.
